name: Build Paper Plugin
on: push
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: chmod +x gradlew  # Fix permissions
      - run: ./gradlew shadowJar
      - uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: build/libs/*.jar
