
name: Build Paper Plugin
on: push
permissions:
  actions: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'  # Changed from 17 to 21
          distribution: 'temurin'
      - run: ./gradlew shadowJar
      - uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: build/libs/*.jar
