name: Build Paper Plugin
on: push
permissions:
  actions: write  # Required for artifact uploads
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 17
      - run: ./gradlew shadowJar
      - uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: build/libs/*.jar
