name: Build Paper Plugin
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Generate Gradle Wrapper
      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.7 --distribution-type bin
          chmod +x gradlew  # Make wrapper executable

      - name: Build Plugin
        run: ./gradlew shadowJar

      - uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: build/libs/*.jar
